# Generated by Django 5.2 on 2025-04-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"managed": False},
        ),
    ]
